version: "3"

volumes:
  pgdata:

services:
  app:
    build:
      context: .
    image: aastashov/tracker_bro:latest
    environment:
      TG_TOKEN: ""
    volumes:
      - ./database.json:/srv/app/database.json

  postgres:
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_DB: tracker_bro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass1234
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
